/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;
import Clases.*;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author Silva
 */
public class Licencias_Consumo extends javax.swing.JDialog {
Controlador control = new Controlador();
Mimodelo modelo = new Mimodelo();
String idcronog="", idpago="",almu="";
    /**
     * Creates new form NewJDialog
     */
    public Licencias_Consumo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //jTable1.setModel(modelo);
        this.setTitle("Agregar Una Licencia");
       control.LlenarCombo(cbTipoDocumento,"select * from tipocomprobante",2);
       jDateChooser1.setDate(new Date());
        //control.forma_table_ver(modelo, jTable1);
        //FormatoTabla ft=new FormatoTabla(1);
        //jTable1.setDefaultRenderer(Object.class, ft);
    jDateChooser1.setMinSelectableDate(new Date());
    }
public void llenardatos(String idpag,String al){
    if(al.equals("Todo")){
        almu="0";
    }else{
        almu="1";
    }
    idcronog=idpag;
    control.Sql=String.format("SELECT idcronogramaconsumo, idpago, fechaconsumo, estadocrono,dayname(fechaconsumo) FROM cronogramaconsumo c where idcronogramaconsumo='%s';", idpag);
    System.out.println(String.format("SELECT idcronogramaconsumo, idpago, fechaconsumo, estadocrono,dayname(fechaconsumo) FROM cronogramaconsumo c where idcronogramaconsumo='%s';", idpag));
    lbFechamod.setText(control.DevolverRegistroDto(control.Sql,3));
    lbDiamodif.setText(control.diasespañol(control.DevolverRegistroDto(control.Sql,5)));
    idpago=control.DevolverRegistroDto(control.Sql,2);
    //int idtipco=Integer.parseInt(control.DevolverRegistroDto(control.Sql,1));    

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbFechamod = new javax.swing.JLabel();
        lbDiamodif = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbTipoDocumento = new javax.swing.JComboBox();
        jtxNumDoc = new javax.swing.JTextField();
        txMotivo = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Generales", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 51, 102))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbFechamod.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lbFechamod.setForeground(new java.awt.Color(204, 51, 0));
        lbFechamod.setText(" ");
        lbFechamod.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(lbFechamod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 290, 20));

        lbDiamodif.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lbDiamodif.setForeground(new java.awt.Color(204, 51, 0));
        lbDiamodif.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(lbDiamodif, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 290, 20));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("FECHA A MODIFICAR");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("DIA A MODIFICAR");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("TIPO DE DOCUMENTO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 153));
        jLabel13.setText("N° DOCUMENTO");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 20));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 153));
        jLabel14.setText("MOTIVO");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("NUEVA FECHA");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 20));

        jPanel2.add(cbTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 290, -1));
        jPanel2.add(jtxNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 290, -1));
        jPanel2.add(txMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 290, -1));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 290, -1));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 51, 102))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 10, 120, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Accept.png"))); // NOI18N
        jButton2.setText("ACEPTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GrabarLicencia();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CargarCronograma();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Licencias_Consumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Licencias_Consumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Licencias_Consumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Licencias_Consumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Licencias_Consumo dialog = new Licencias_Consumo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbTipoDocumento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jtxNumDoc;
    private javax.swing.JLabel lbDiamodif;
    private javax.swing.JLabel lbFechamod;
    private javax.swing.JTextField txMotivo;
    // End of variables declaration//GEN-END:variables

    private void GrabarLicencia() {
        if(cbTipoDocumento.getSelectedIndex()>=0 && txMotivo.getText().trim().length()>0 && jtxNumDoc.getText().trim().length()>0){
            try {
                control.Sql=String.format("select idpago from cronogramaconsumo where idcronogramaconsumo='%s';", idcronog);
                String idpgo=control.DevolverRegistroDto(control.Sql,1);
                control.Sql=String.format("select count(*) from cronogramaconsumo where fechaconsumo='%s' and idpago='%s';", control.Formato_Amd(jDateChooser1.getDate()),idpago);
                int verd=Integer.parseInt(control.DevolverRegistroDto(control.Sql, 1));
                if(verd==0){
                    /*Inserta Registro Licencia*/
                    control.Sql=String.format("insert into licencias values(null,'%s','%s','%s','%s','%s');",
                    txMotivo.getText(),jtxNumDoc.getText(),control.Formato_Amd(jDateChooser1.getDate()),idcronog,control.DevolverRegistroDto("select idtipocomprobante from tipocomprobante where descricomproba='"+cbTipoDocumento.getSelectedItem().toString()+"';", 1));
                    control.CrearRegistro(control.Sql);
                    /*inserta Nuevo Cronograma*/
                    control.Sql=String.format("insert into cronogramaconsumo  values(null,'%s','%s','0','"+almu+"');",idpgo,control.Formato_Amd(jDateChooser1.getDate()));
                    control.CrearRegistro(control.Sql);
                    /*Editar Cronograma Anterior*/
                    control.Sql="update cronogramaconsumo set estadocrono='2' where idcronogramaconsumo='"+idcronog+"';";
                    control.EditarRegistro(control.Sql);
                    JOptionPane.showMessageDialog(null, "Se Grabo la Licencia con Exitos","System Message",3);
                    CargarCronograma();
                }else{
                    JOptionPane.showMessageDialog(null, "El Comensal ya tiene Asignado este Dia Selecion de Nuevo");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese Datos completos");
        }
    }

    private void CargarCronograma() {
        this.dispose();
        Ver_Cronograma verc=new Ver_Cronograma(null, true);
        verc.setLocationRelativeTo(this);
        verc.llenardatos(idpago);
        verc.setVisible(true);
    }
}
